# 给node_modules设置缓存，这样就不用每次重新安装依赖，加快速度。
cache:
  paths:
    - node_modules/

# 在开始跑脚本之前，需要设置环境变量。主要为暴露：
# cnpm，npm，node
before_script:
  - node -v
  - which node
  - yarn config set registry http://10.80.84.176:4873/
  - nvm use 12.18.3 && yarn install
  - whoami

stages:
  - deploy_dev

deploy_dev:
  stage: deploy_dev
  tags:
    - fed-builder-s1
  environment:
    # 指定当前job的运行环境，$CI_COMMIT_REF_NAME代表当前分支名
    name: dev/$CI_COMMIT_REF_NAME
  script:
    - nvm use 12.18.3 && yarn build
